/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BatchBatchActions: typeof import('./components/batch/BatchActions.vue')['default']
    BatchBatchClippingCard: typeof import('./components/batch/BatchClippingCard.vue')['default']
    BatchBatchWarnings: typeof import('./components/batch/BatchWarnings.vue')['default']
    BooksBookCard: typeof import('./components/books/BookCard.vue')['default']
    BooksBookList: typeof import('./components/books/BookList.vue')['default']
    BooksBookListItem: typeof import('./components/books/BookListItem.vue')['default']
    ClippingsClippingCard: typeof import('./components/clippings/ClippingCard.vue')['default']
    ClippingsClippingList: typeof import('./components/clippings/ClippingList.vue')['default']
    EditorDataTable: typeof import('./components/editor/DataTable.vue')['default']
    ExportExportPanel: typeof import('./components/export/ExportPanel.vue')['default']
    ExportFormatPicker: typeof import('./components/export/FormatPicker.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ImportImportOptions: typeof import('./components/import/ImportOptions.vue')['default']
    LayoutAppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    LayoutAppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    LayoutMobileMenu: typeof import('./components/layout/MobileMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsActivityChart: typeof import('./components/stats/ActivityChart.vue')['default']
    StatsInsightsPanel: typeof import('./components/stats/InsightsPanel.vue')['default']
    StatsStatCard: typeof import('./components/stats/StatCard.vue')['default']
    StatsTopBooksChart: typeof import('./components/stats/TopBooksChart.vue')['default']
    StatsTypeDistributionChart: typeof import('./components/stats/TypeDistributionChart.vue')['default']
    UiConfirmModal: typeof import('./components/ui/ConfirmModal.vue')['default']
    UiEmptyState: typeof import('./components/ui/EmptyState.vue')['default']
    UiSkeleton: typeof import('./components/ui/Skeleton.vue')['default']
    UiToastContainer: typeof import('./components/ui/ToastContainer.vue')['default']
    UiTooltip: typeof import('./components/ui/Tooltip.vue')['default']
  }
}
