/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/batch/': RouteRecordInfo<
      '/batch/',
      '/batch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/batch/[id]': RouteRecordInfo<
      '/batch/[id]',
      '/batch/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/books/[id]': RouteRecordInfo<
      '/books/[id]',
      '/books/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/editor': RouteRecordInfo<
      '/editor',
      '/editor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/export': RouteRecordInfo<
      '/export',
      '/export',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/import': RouteRecordInfo<
      '/import',
      '/import',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/library': RouteRecordInfo<
      '/library',
      '/library',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/search': RouteRecordInfo<
      '/search',
      '/search',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/batch/index.vue': {
      routes:
        | '/batch/'
      views:
        | never
    }
    'src/pages/batch/[id].vue': {
      routes:
        | '/batch/[id]'
      views:
        | never
    }
    'src/pages/books/[id].vue': {
      routes:
        | '/books/[id]'
      views:
        | never
    }
    'src/pages/editor.vue': {
      routes:
        | '/editor'
      views:
        | never
    }
    'src/pages/export.vue': {
      routes:
        | '/export'
      views:
        | never
    }
    'src/pages/import.vue': {
      routes:
        | '/import'
      views:
        | never
    }
    'src/pages/library.vue': {
      routes:
        | '/library'
      views:
        | never
    }
    'src/pages/search.vue': {
      routes:
        | '/search'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
